spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/NBA
spring.datasource.username=postgres
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


server.servlet.context-path=/api/v1
server.port=8085

jwt.jwtSecret=fskjfsdlgjewojewfewopkngdkjfskdlfjsdfklsghskdgeowhjgweghsfjgsldkfjsdlfsdfs
jwt.jwtExpirationMs=3600000
jwt.jwtRefreshExpirationMs=86400000

# logging.level.org.springframework=DEBUG
# logging.level.com.portal.backend=DEBUG

# Spring Security core logs
logging.level.org.springframework.security=TRACE

# For authentication details (AuthenticationManager, ProviderManager, etc.)
logging.level.org.springframework.security.authentication=TRACE

# For filter chain (UsernamePasswordAuthenticationFilter, JwtAuthenticationFilter, etc.)
logging.level.org.springframework.security.web=TRACE

# For your own package
logging.level.com.portal.backend=DEBUG
